version: "3"

services:
  database-postgres:
    container_name: database-postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  backend:
    container_name: backend
    env_file: ./backend/.env
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - database-postgres

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "8080:8080"